# source(here::here("p_prototype_schema/inception database.R"))
# source(here::here("p_prototype_schema/steps.R"))
source(here::here("p_prototype_schema/populate codebooks.R"))
source(here::here("p_prototype_schema/populate index file.R"))
source(here::here("p_prototype_schema/populate variables.R"))
# source(here::here("p_prototype_schema/parameters.R"))
# source(here::here("p_prototype_schema/configuration files.R"))
# source(here::here("p_prototype_schema/dag.R"))
source(here::here("p_prototype_schema/schema and pipeline.R"))

